version: 0.0
os: linux
file_exists_behavior: OVERWRITE
files:
  - source: /
    destination: /home/ec2-user/app/image-api

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user
  AfterInstall:
    - location: scripts/install.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 100
      runas: ec2-user
