version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 800
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 100
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 100
      runas: ec2-user
