version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_URI:latest .
  post_build:
    commands:
      - echo Pushing to ECR...
      - docker push $ECR_REPO_URI:latest
      - echo Writing image definition...
      - printf '[{"name":"grovio-app","imageUri":"%s:latest"}]' $ECR_REPO_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - scripts/*
