IMAGE_MODELS = [
    {
        "model_id": 'clarity-upscaler',
        "name": 'CLARITY_UPSCALER',
        "fal_endpoint": 'fal-ai/clarity-upscaler',
        "description": 'Clarity Upscaler - Sharpness and detail enhancement',
        "credits": 3,
        "price_per_mp": 0.02,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'Upscale and enhance this image to higher resolution while maintaining sharpness and adding realistic detail. Preserve the original composition and style. Remove compression artifacts, enhance textures, and improve overall clarity. Suitable for print, large displays, or high-resolution viewing.',
        "supported_sizes": {'family': 'upscale', 'sizes': ['Up to 4x input size'], 'aspect_ratios': ['Preserves input aspect ratio'], 'max_resolution': '4096x4096', 'notes': 'Output size = input size × scale factor (1-4x)'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'creative-upscaler',
        "name": 'CREATIVE_UPSCALER',
        "fal_endpoint": 'fal-ai/creative-upscaler',
        "description": 'Creative Upscaler - AI enhancement and upscaling',
        "credits": 3,
        "price_per_mp": 0.02,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'Upscale and enhance this image to higher resolution while maintaining sharpness and adding realistic detail. Preserve the original composition and style. Remove compression artifacts, enhance textures, and improve overall clarity. Suitable for print, large displays, or high-resolution viewing.',
        "supported_sizes": {'family': 'upscale', 'sizes': ['Up to 4x input size'], 'aspect_ratios': ['Preserves input aspect ratio'], 'max_resolution': '4096x4096', 'notes': 'Output size = input size × scale factor (1-4x)'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'dreamina-v3.1',
        "name": 'DREAMINA_V31',
        "fal_endpoint": 'fal-ai/bytedance/dreamina/v3.1/text-to-image',
        "description": 'ByteDance Dreamina V3.1 - Specialized portrait generation',
        "credits": 3,
        "price_per_mp": 0.027,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'flux2-dev',
        "name": 'FLUX2_DEV',
        "fal_endpoint": 'fal-ai/flux-2',
        "description": 'FLUX.2 Dev - High quality generation from Black Forest Labs',
        "credits": 2,
        "price_per_mp": 0.012,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'Eye-catching social media content, vibrant colors, engaging composition, modern design, scroll-stopping visual',
        "supported_sizes": {'family': 'flux2', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576', '1536x640', '640x1536'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9', '21:9', '9:21'], 'max_resolution': '1536x1536', 'notes': 'Supports custom dimensions up to 1536px'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'flux2-dev-edit',
        "name": 'FLUX2_DEV_EDIT',
        "fal_endpoint": 'fal-ai/flux-2/edit',
        "description": 'FLUX.2 Dev Edit - Image editing with natural language',
        "credits": 3,
        "price_per_mp": 0.024,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 3,
        "max_output_images": 4,
        "sample_prompt": 'Edit for marketing variation, maintain brand consistency, professional quality',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'flux2-pro',
        "name": 'FLUX2_PRO',
        "fal_endpoint": 'fal-ai/flux-2-pro',
        "description": 'FLUX.2 Pro - Maximum quality from Black Forest Labs',
        "credits": 5,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 1,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'flux2', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576', '1536x640', '640x1536'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9', '21:9', '9:21'], 'max_resolution': '1536x1536', 'notes': 'Supports custom dimensions up to 1536px'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'flux2-pro-edit',
        "name": 'FLUX2_PRO_EDIT',
        "fal_endpoint": 'fal-ai/flux-2-pro/edit',
        "description": 'FLUX.2 Pro Edit - Premium image editing',
        "credits": 5,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 3,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'gemini-3-pro',
        "name": 'GEMINI3_PRO',
        "fal_endpoint": 'fal-ai/gemini-3-pro-image-preview',
        "description": 'Nano Banana Pro - Realism and typography with web search',
        "credits": 7,
        "price_per_mp": 0.15,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'nano-banana', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9'], 'max_resolution': '1024x1024', 'notes': "Google's Gemini-based model"},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'gemini-3-pro-edit',
        "name": 'GEMINI3_PRO_EDIT',
        "fal_endpoint": 'fal-ai/gemini-3-pro-image-preview/edit',
        "description": 'Nano Banana Pro Edit - Multi-image editing',
        "credits": 7,
        "price_per_mp": 0.15,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 10,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'gpt-image-1.5',
        "name": 'GPT_IMAGE_15',
        "fal_endpoint": 'fal-ai/gpt-image-1.5',
        "description": 'GPT Image 1.5 - Photorealistic generation with transparent backgrounds',
        "credits": 6,
        "price_per_mp": 0.05,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'gpt-image-1.5-edit',
        "name": 'GPT_IMAGE_15_EDIT',
        "fal_endpoint": 'fal-ai/gpt-image-1.5/edit',
        "description": 'GPT Image 1.5 Edit - Multi-image editing with transparent backgrounds',
        "credits": 6,
        "price_per_mp": 0.05,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 10,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'ideogram-v3',
        "name": 'IDEOGRAM_V3',
        "fal_endpoint": 'fal-ai/ideogram/v3',
        "description": 'Ideogram V3 - Superior typography and style presets',
        "credits": 6,
        "price_per_mp": 0.08,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'ideogram', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576', '1024x1536', '1536x1024'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9', '2:3', '3:2'], 'max_resolution': '1536x1536', 'notes': 'Best for logos and text-heavy images'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'ideogram-v3-reframe',
        "name": 'IDEOGRAM_V3_REFRAME',
        "fal_endpoint": 'fal-ai/ideogram/v3/reframe',
        "description": 'Ideogram V3 Reframe - Image resizing and outpainting',
        "credits": 6,
        "price_per_mp": 0.08,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'multiple-angles',
        "name": 'QWEN_MULTIPLE_ANGLES',
        "fal_endpoint": 'fal-ai/qwen-image-edit-2509-lora-gallery/multiple-angles',
        "description": 'Qwen Multiple Angles - Generate multi-view perspectives',
        "credits": 5,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 8,
        "sample_prompt": 'Generate multiple camera angles of this character, front view, side view, back view, consistent character sheet style',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'recraft-upscale',
        "name": 'RECRAFT_UPSCALE',
        "fal_endpoint": 'fal-ai/recraft/upscale/creative',
        "description": 'Recraft Upscale - Vector-style creative upscaling',
        "credits": 3,
        "price_per_mp": 0.02,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'Upscale and enhance this image to higher resolution while maintaining sharpness and adding realistic detail. Preserve the original composition and style. Remove compression artifacts, enhance textures, and improve overall clarity. Suitable for print, large displays, or high-resolution viewing.',
        "supported_sizes": {'family': 'upscale', 'sizes': ['Up to 4x input size'], 'aspect_ratios': ['Preserves input aspect ratio'], 'max_resolution': '4096x4096', 'notes': 'Output size = input size × scale factor (1-4x)'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve',
        "name": 'REVE',
        "fal_endpoint": 'fal-ai/reve/text-to-image',
        "description": 'Reve - State-of-the-art generation',
        "credits": 4,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve-edit',
        "name": 'REVE_EDIT',
        "fal_endpoint": 'fal-ai/reve/edit',
        "description": 'Reve Edit - Professional image editing',
        "credits": 4,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve-fast-edit',
        "name": 'REVE_FAST_EDIT',
        "fal_endpoint": 'fal-ai/reve/fast/edit',
        "description": 'Reve Fast Edit - Quick iteration editing',
        "credits": 4,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve-fast-remix',
        "name": 'REVE_FAST_REMIX',
        "fal_endpoint": 'fal-ai/reve/fast/remix',
        "description": 'Reve Fast Remix - Quick multi-image remixing',
        "credits": 4,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 6,
        "max_output_images": 4,
        "sample_prompt": 'Fast creative remix, professional quality, quick output',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve-remix',
        "name": 'REVE_REMIX',
        "fal_endpoint": 'fal-ai/reve/remix',
        "description": 'Reve Remix - Creative multi-image composition',
        "credits": 4,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 6,
        "max_output_images": 4,
        "sample_prompt": 'Creative multi-image remix, seamless composition, marketing-ready',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'seedream-v4',
        "name": 'SEEDREAM_V4',
        "fal_endpoint": 'fal-ai/bytedance/seedream/v4/text-to-image',
        "description": 'ByteDance Seedream V4 - 4K High Resolution Generation',
        "credits": 5,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 6,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'seedream-v4-edit',
        "name": 'SEEDREAM_V4_EDIT',
        "fal_endpoint": 'fal-ai/bytedance/seedream/v4/edit',
        "description": 'ByteDance Seedream V4 Edit - 4K High Resolution Editing',
        "credits": 5,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 10,
        "max_output_images": 6,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'seedream-v4.5',
        "name": 'SEEDREAM_V45',
        "fal_endpoint": 'fal-ai/bytedance/seedream/v4.5/text-to-image',
        "description": 'ByteDance Seedream V4.5 - Stylized content generation',
        "credits": 4,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'seedream', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9'], 'max_resolution': '1024x1024', 'notes': "ByteDance's latest model"},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'seedream-v4.5-edit',
        "name": 'SEEDREAM_V45_EDIT',
        "fal_endpoint": 'fal-ai/bytedance/seedream/v4.5/edit',
        "description": 'ByteDance Seedream Edit - Multi-image editing',
        "credits": 4,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 3,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'z-image-turbo',
        "name": 'Z_IMAGE_TURBO',
        "fal_endpoint": 'fal-ai/z-image/turbo',
        "description": 'Z-Image Turbo - Ultra fast 6B model from Tongyi-MAI',
        "credits": 1,
        "price_per_mp": 0.005,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'z-image', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9'], 'max_resolution': '1024x1024', 'notes': 'Ultra-fast 6B model from Tongyi-MAI'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
]
