"""
Seed Script for Image Models Database
Populates the Image_Models collection with all models and their credit costs.

Usage:
    python3 seed_models.py
"""

import os
from datetime import datetime, timezone

# MongoDB imports - using pymongo (sync) instead of motor for simpler seeding
from pymongo import MongoClient

# =============================================================================
# TIER DEFINITIONS (Based on subscription plans)
# =============================================================================
# Starter: $19/mo 9,000 credits
# Pro: $49/mo 24,000 credits  
# Creator: $99/mo 48,000 credits
# Team/Studio: $199/mo 97,000 credits

TIERS = {
    "Starter": {"price": 19, "credits": 9000},
    "Pro": {"price": 49, "credits": 24000},
    "Creator": {"price": 99, "credits": 48000},
    "Team": {"price": 199, "credits": 97000},
}

# =============================================================================
# SIZE CREDIT MULTIPLIERS
# Smaller sizes cost less, larger sizes cost more
# =============================================================================
SIZE_MULTIPLIERS = {
    "512x512": 1.0,
    "768x1024": 1.0,
    "576x1024": 1.0,
    "1024x768": 1.0,
    "1024x576": 1.0,
    "1024x1024": 1.0,
    "1536x640": 1.0,
    "640x1536": 1.0,
    "1024x1536": 1.6,
    "1536x1024": 1.6,
    "2048x2048": 2.2,
    "4096x4096": 2.2,
}

# =============================================================================
# IMAGE MODELS - Complete list with credit costs
# =============================================================================
IMAGE_MODELS = [
    {
        "model_id": 'clarity-upscaler',
        "name": 'CLARITY_UPSCALER',
        "fal_endpoint": 'fal-ai/clarity-upscaler',
        "description": 'Clarity Upscaler - Sharpness and detail enhancement',
        "credits": 30,
        "price_per_mp": 0.02,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'Upscale and enhance this image to higher resolution while maintaining sharpness and adding realistic detail. Preserve the original composition and style. Remove compression artifacts, enhance textures, and improve overall clarity. Suitable for print, large displays, or high-resolution viewing.',
        "supported_sizes": {'family': 'upscale', 'sizes': ['Up to 4x input size'], 'aspect_ratios': ['Preserves input aspect ratio'], 'max_resolution': '4096x4096', 'notes': 'Output size = input size × scale factor (1-4x)'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'creative-upscaler',
        "name": 'CREATIVE_UPSCALER',
        "fal_endpoint": 'fal-ai/creative-upscaler',
        "description": 'Creative Upscaler - AI enhancement and upscaling',
        "credits": 40,
        "price_per_mp": 0.02,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'Upscale and enhance this image to higher resolution while maintaining sharpness and adding realistic detail. Preserve the original composition and style. Remove compression artifacts, enhance textures, and improve overall clarity. Suitable for print, large displays, or high-resolution viewing.',
        "supported_sizes": {'family': 'upscale', 'sizes': ['Up to 4x input size'], 'aspect_ratios': ['Preserves input aspect ratio'], 'max_resolution': '4096x4096', 'notes': 'Output size = input size × scale factor (1-4x)'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'dreamina-v3.1',
        "name": 'DREAMINA_V31',
        "fal_endpoint": 'fal-ai/bytedance/dreamina/v3.1/text-to-image',
        "description": 'ByteDance Dreamina V3.1 - Specialized portrait generation',
        "credits": 40,
        "price_per_mp": 0.027,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'flux2-dev',
        "name": 'FLUX2_DEV',
        "fal_endpoint": 'fal-ai/flux-2',
        "description": 'FLUX.2 Dev - High quality generation from Black Forest Labs',
        "credits": 20,
        "price_per_mp": 0.012,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'Eye-catching social media content, vibrant colors, engaging composition, modern design, scroll-stopping visual',
        "supported_sizes": {'family': 'flux2', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576', '1536x640', '640x1536'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9', '21:9', '9:21'], 'max_resolution': '1536x1536', 'notes': 'Supports custom dimensions up to 1536px'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'flux2-dev-edit',
        "name": 'FLUX2_DEV_EDIT',
        "fal_endpoint": 'fal-ai/flux-2/edit',
        "description": 'FLUX.2 Dev Edit - Image editing with natural language',
        "credits": 35,
        "price_per_mp": 0.024,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 3,
        "max_output_images": 4,
        "sample_prompt": 'Edit for marketing variation, maintain brand consistency, professional quality',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'flux2-pro',
        "name": 'FLUX2_PRO',
        "fal_endpoint": 'fal-ai/flux-2-pro',
        "description": 'FLUX.2 Pro - Maximum quality from Black Forest Labs',
        "credits": 40,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 1,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'flux2', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576', '1536x640', '640x1536'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9', '21:9', '9:21'], 'max_resolution': '1536x1536', 'notes': 'Supports custom dimensions up to 1536px'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'flux2-pro-edit',
        "name": 'FLUX2_PRO_EDIT',
        "fal_endpoint": 'fal-ai/flux-2-pro/edit',
        "description": 'FLUX.2 Pro Edit - Premium image editing',
        "credits": 40,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 3,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'gemini-3-pro',
        "name": 'GEMINI3_PRO',
        "fal_endpoint": 'fal-ai/gemini-3-pro-image-preview',
        "description": 'Nano Banana Pro - Realism and typography with web search',
        "credits": 200,
        "price_per_mp": 0.15,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'nano-banana', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9'], 'max_resolution': '1024x1024', 'notes': "Google's Gemini-based model"},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'gemini-3-pro-edit',
        "name": 'GEMINI3_PRO_EDIT',
        "fal_endpoint": 'fal-ai/gemini-3-pro-image-preview/edit',
        "description": 'Nano Banana Pro Edit - Multi-image editing',
        "credits": 200,
        "price_per_mp": 0.15,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 10,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'gpt-image-1.5',
        "name": 'GPT_IMAGE_15',
        "fal_endpoint": 'fal-ai/gpt-image-1.5',
        "description": 'GPT Image 1.5 - Photorealistic generation with transparent backgrounds',
        "credits": 55,
        "price_per_mp": 0.05,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'gpt-image-1.5-edit',
        "name": 'GPT_IMAGE_15_EDIT',
        "fal_endpoint": 'fal-ai/gpt-image-1.5/edit',
        "description": 'GPT Image 1.5 Edit - Multi-image editing with transparent backgrounds',
        "credits": 55,
        "price_per_mp": 0.05,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 10,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'ideogram-v3',
        "name": 'IDEOGRAM_V3',
        "fal_endpoint": 'fal-ai/ideogram/v3',
        "description": 'Ideogram V3 - Superior typography and style presets',
        "credits": 40,
        "price_per_mp": 0.08,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'ideogram', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576', '1024x1536', '1536x1024'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9', '2:3', '3:2'], 'max_resolution': '1536x1536', 'notes': 'Best for logos and text-heavy images'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'ideogram-v3-reframe',
        "name": 'IDEOGRAM_V3_REFRAME',
        "fal_endpoint": 'fal-ai/ideogram/v3/reframe',
        "description": 'Ideogram V3 Reframe - Image resizing and outpainting',
        "credits": 40,
        "price_per_mp": 0.08,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'multiple-angles',
        "name": 'QWEN_MULTIPLE_ANGLES',
        "fal_endpoint": 'fal-ai/qwen-image-edit-2509-lora-gallery/multiple-angles',
        "description": 'Qwen Multiple Angles - Generate multi-view perspectives',
        "credits": 65,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 8,
        "sample_prompt": 'Generate multiple camera angles of this character, front view, side view, back view, consistent character sheet style',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'recraft-upscale',
        "name": 'RECRAFT_UPSCALE',
        "fal_endpoint": 'fal-ai/recraft/upscale/creative',
        "description": 'Recraft Upscale - Vector-style creative upscaling',
        "credits": 30,
        "price_per_mp": 0.02,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'Upscale and enhance this image to higher resolution while maintaining sharpness and adding realistic detail. Preserve the original composition and style. Remove compression artifacts, enhance textures, and improve overall clarity. Suitable for print, large displays, or high-resolution viewing.',
        "supported_sizes": {'family': 'upscale', 'sizes': ['Up to 4x input size'], 'aspect_ratios': ['Preserves input aspect ratio'], 'max_resolution': '4096x4096', 'notes': 'Output size = input size × scale factor (1-4x)'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve',
        "name": 'REVE',
        "fal_endpoint": 'fal-ai/reve/text-to-image',
        "description": 'Reve - State-of-the-art generation',
        "credits": 55,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve-edit',
        "name": 'REVE_EDIT',
        "fal_endpoint": 'fal-ai/reve/edit',
        "description": 'Reve Edit - Professional image editing',
        "credits": 55,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve-fast-edit',
        "name": 'REVE_FAST_EDIT',
        "fal_endpoint": 'fal-ai/reve/fast/edit',
        "description": 'Reve Fast Edit - Quick iteration editing',
        "credits": 55,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 1,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve-fast-remix',
        "name": 'REVE_FAST_REMIX',
        "fal_endpoint": 'fal-ai/reve/fast/remix',
        "description": 'Reve Fast Remix - Quick multi-image remixing',
        "credits": 55,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 6,
        "max_output_images": 4,
        "sample_prompt": 'Fast creative remix, professional quality, quick output',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'reve-remix',
        "name": 'REVE_REMIX',
        "fal_endpoint": 'fal-ai/reve/remix',
        "description": 'Reve Remix - Creative multi-image composition',
        "credits": 55,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 6,
        "max_output_images": 4,
        "sample_prompt": 'Creative multi-image remix, seamless composition, marketing-ready',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'seedream-v4',
        "name": 'SEEDREAM_V4',
        "fal_endpoint": 'fal-ai/bytedance/seedream/v4/text-to-image',
        "description": 'ByteDance Seedream V4 - 4K High Resolution Generation',
        "credits": 40,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 6,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'general', 'sizes': ['1024x1024', '768x1024', '1024x768'], 'aspect_ratios': ['1:1', '3:4', '4:3'], 'max_resolution': '1024x1024', 'notes': 'Size typically inherited from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'seedream-v4-edit',
        "name": 'SEEDREAM_V4_EDIT',
        "fal_endpoint": 'fal-ai/bytedance/seedream/v4/edit',
        "description": 'ByteDance Seedream V4 Edit - 4K High Resolution Editing',
        "credits": 40,
        "price_per_mp": 0.03,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 10,
        "max_output_images": 6,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'seedream-v4.5',
        "name": 'SEEDREAM_V45',
        "fal_endpoint": 'fal-ai/bytedance/seedream/v4.5/text-to-image',
        "description": 'ByteDance Seedream V4.5 - Stylized content generation',
        "credits": 55,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'seedream', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9'], 'max_resolution': '1024x1024', 'notes': "ByteDance's latest model"},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'seedream-v4.5-edit',
        "name": 'SEEDREAM_V45_EDIT',
        "fal_endpoint": 'fal-ai/bytedance/seedream/v4.5/edit',
        "description": 'ByteDance Seedream Edit - Multi-image editing',
        "credits": 55,
        "price_per_mp": 0.04,
        "tier": None,
        "is_edit_model": True,
        "enabled": True,
        "max_input_images": 3,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'editing', 'sizes': [], 'aspect_ratios': [], 'max_resolution': 'Same as input', 'notes': 'Inherits size and aspect ratio from input image'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
    {
        "model_id": 'z-image-turbo',
        "name": 'Z_IMAGE_TURBO',
        "fal_endpoint": 'fal-ai/z-image/turbo',
        "description": 'Z-Image Turbo - Ultra fast 6B model from Tongyi-MAI',
        "credits": 8,
        "price_per_mp": 0.005,
        "tier": None,
        "is_edit_model": False,
        "enabled": True,
        "max_input_images": 0,
        "max_output_images": 4,
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "supported_sizes": {'family': 'z-image', 'sizes': ['1024x1024', '768x1024', '576x1024', '1024x768', '1024x576'], 'aspect_ratios': ['1:1', '3:4', '9:16', '4:3', '16:9'], 'max_resolution': '1024x1024', 'notes': 'Ultra-fast 6B model from Tongyi-MAI'},
        "model_size": SIZE_MULTIPLIERS.copy(),
    },
]


USE_CASES = [
    {
        "use_case_id": 'character-multiple-angles',
        "name": 'Character Multiple Angles',
        "description": 'Recommended models for Character Multiple Angles',
        "models": ['multiple-angles'],
        "system_prompt": 'Generate multiple camera angles of this character/product while maintaining consistency. Each angle shows the same subject from a different perspective for 360-degree visualization.',
        "sample_prompt": 'Generate multiple camera angles of this character, front view, side view, back view, consistent character sheet style',
        "prompt_tips": ['Use a clear, high-quality input image', 'Works best with single subjects (characters, products)', 'Generates 8 different angles automatically', 'Perfect for product showcases and character turnarounds', 'Maintains subject consistency across all angles'],
        "notes": 'Generates 8 images in parallel from a single input. Uses Qwen Image Edit model with precise camera control. Cost: ~$0.24 for all 8 angles.',
        "enabled": True,
    },
    {
        "use_case_id": 'create-images',
        "name": 'Create Images',
        "description": 'Recommended models for Create Images',
        "models": ['flux2-pro', 'flux2-dev', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "notes": 'All 10 text-to-image models. Use flux2-dev for balanced quality/speed, z-image-turbo for fastest, gemini-3-pro for typography, reve for state-of-the-art, gpt-image-1.5 for transparent backgrounds.',
        "enabled": True,
    },
    {
        "use_case_id": 'display-ads',
        "name": 'Display Ads',
        "description": 'Recommended models for Display Ads',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create eye-catching display advertisement imagery. High impact visual that works at small sizes. Clear brand message, strong call-to-action placement area. Scalable design that maintains clarity when resized. Professional advertising quality suitable for programmatic display networks.',
        "sample_prompt": 'Sleek modern laptop on a clean desk, space for text on the right, blue gradient background, tech concept, high resolution, professional advertising',
        "prompt_tips": ['High impact, works at small sizes', 'Clear focal point visible at any scale', 'Space for CTA button or text', 'Professional advertising quality', 'Consistent with brand guidelines'],
        "platform_sizes": {'medium_rectangle': {'width': 300, 'height': 250, 'aspect_ratio': '6:5', 'closest_size': '1024x1024', 'notes': 'IAB Medium Rectangle (300x250)'}, 'leaderboard': {'width': 728, 'height': 90, 'aspect_ratio': '8:1', 'closest_size': '1536x640', 'notes': 'IAB Leaderboard (728x90)'}, 'large_rectangle': {'width': 336, 'height': 280, 'aspect_ratio': '6:5', 'closest_size': '1024x1024', 'notes': 'IAB Large Rectangle (336x280)'}, 'wide_skyscraper': {'width': 160, 'height': 600, 'aspect_ratio': '4:15', 'closest_size': '640x1536', 'notes': 'IAB Wide Skyscraper (160x600)'}, 'billboard': {'width': 970, 'height': 250, 'aspect_ratio': '4:1', 'closest_size': '1536x640', 'notes': 'Billboard format (970x250)'}},
        "recommended_size": 'medium_rectangle',
        "notes": 'Generate at high resolution, then resize to exact ad dimensions',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'edit-images',
        "name": 'Edit Images',
        "description": 'Recommended models for Edit Images',
        "models": ['flux2-pro-edit', 'flux2-dev-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'reve-remix', 'reve-fast-remix', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
        "notes": 'All 10 image editing models. Use reve-edit for general editing, gemini-3-pro-edit for multi-image, reve-remix for combining images, ideogram-v3-reframe for aspect ratio changes.',
        "enabled": True,
    },
    {
        "use_case_id": 'facebook-ads',
        "name": 'Facebook Ads',
        "description": 'Recommended models for Facebook Ads',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create a high-converting Facebook ad image. Clear focal point, compelling visual that communicates value instantly. Minimal text (Facebook penalizes text-heavy images). Emotionally resonant imagery that triggers action. Professional quality suitable for paid advertising.',
        "sample_prompt": 'Professional product shot of a premium skincare bottle on a marble podium, water droplets, soft pastel background, studio lighting, 4k resolution',
        "prompt_tips": ['Clear, single focal point', 'Emotionally compelling imagery', 'Minimal text in image (less than 20%)', 'High contrast for feed visibility', 'Professional, trustworthy aesthetic'],
        "platform_sizes": {'feed_square': {'width': 1080, 'height': 1080, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Standard feed ad'}, 'feed_portrait': {'width': 1080, 'height': 1350, 'aspect_ratio': '4:5', 'closest_size': '768x1024', 'notes': 'Better engagement on mobile'}, 'story': {'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'closest_size': '576x1024', 'notes': 'Facebook Story ad'}, 'landscape': {'width': 1200, 'height': 628, 'aspect_ratio': '1.91:1', 'closest_size': '1024x576', 'notes': 'Link preview / carousel'}},
        "recommended_size": 'feed_portrait',
        "notes": '4:5 portrait performs best on mobile feeds',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'fashion-tryon',
        "name": 'Fashion Tryon',
        "description": 'Recommended models for Fashion Tryon',
        "models": ['seedream-v4.5-edit', 'gpt-image-1.5-edit', 'gemini-3-pro-edit'],
        "system_prompt": "Apply this garment to the person in the image. Preserve the person's pose, body shape, and skin tone. The clothing should fit naturally with realistic wrinkles, shadows, and folds. Blend the garment seamlessly while maintaining photorealistic quality.",
        "sample_prompt": 'Apply this white t-shirt to the person in the image, maintain realistic lighting and fabric folds, seamless blend',
        "notes": 'Upload person image and garment image. Output size inherits from input image.',
        "enabled": True,
    },
    {
        "use_case_id": 'headshots',
        "name": 'Headshots',
        "description": 'Recommended models for Headshots',
        "models": ['reve-edit', 'reve-fast-edit', 'flux2-pro-edit', 'gemini-3-pro-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
        "system_prompt": "Transform this photo into a professional corporate headshot. Keep the person's face and features exactly the same, maintain natural skin texture and authentic appearance. Apply professional studio lighting with soft shadows, clean neutral or gradient background (light gray, white, or subtle blue), sharp focus on face and eyes. Ensure professional attire appearance, natural color grading suitable for LinkedIn/corporate websites. High resolution, photorealistic quality.",
        "sample_prompt": 'Transform this photo into a professional corporate headshot, studio lighting, soft grey background, sharp focus on eyes, business attire',
        "prompt_tips": ['Keep face exactly the same, only change background and lighting', 'Professional studio lighting with soft shadows', 'Clean neutral background (gray, white, or corporate blue)', 'Sharp focus on face and eyes', 'Natural skin texture, no over-smoothing', 'Suitable for LinkedIn, corporate website, business cards'],
        "platform_sizes": {'square': {'width': 800, 'height': 800, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Profile photo format'}, 'portrait': {'width': 800, 'height': 1000, 'aspect_ratio': '4:5', 'closest_size': '768x1024', 'notes': 'Standard headshot'}, 'linkedin_profile': {'width': 400, 'height': 400, 'aspect_ratio': '1:1', 'closest_size': '512x512', 'notes': 'LinkedIn profile (will be cropped circular)'}},
        "recommended_size": 'portrait',
        "notes": "Upload a clear face photo. The AI will transform it into a professional headshot while preserving the person's identity.",
        "enabled": True,
    },
    {
        "use_case_id": 'hero-banners',
        "name": 'Hero Banners',
        "description": 'Recommended models for Hero Banners',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create stunning hero banner imagery for websites. Wide, cinematic composition that spans full browser width. Strong visual narrative with clear focal point. Space for headline text overlay. Premium, professional quality that establishes brand authority. Works across desktop and mobile breakpoints.',
        "sample_prompt": 'Cinematic wide shot of a futuristic city skyline at dusk, purple and orange sky, reflection in water, wide angle lens, extremely detailed, hero banner style',
        "prompt_tips": ['Wide, cinematic composition', 'Clear focal point with negative space for text', 'Premium, brand-establishing quality', 'Works at multiple breakpoints', 'Impactful first impression'],
        "platform_sizes": {'desktop': {'width': 1920, 'height': 600, 'aspect_ratio': '16:5', 'closest_size': '1536x640', 'notes': 'Full-width desktop hero'}, 'mobile': {'width': 750, 'height': 1200, 'aspect_ratio': '5:8', 'closest_size': '768x1024', 'notes': 'Mobile hero banner'}, 'tablet': {'width': 1024, 'height': 768, 'aspect_ratio': '4:3', 'closest_size': '1024x768', 'notes': 'Tablet hero banner'}},
        "recommended_size": 'desktop',
        "notes": 'Create separate assets for desktop/mobile breakpoints',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'image-editing',
        "name": 'Image Editing',
        "description": 'Recommended models for Image Editing',
        "models": ['flux2-dev-edit', 'flux2-pro-edit', 'gemini-3-pro-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'reve-edit', 'reve-fast-edit', 'reve-remix', 'reve-fast-remix'],
        "notes": '9 image editing models. Seedream V4 Edit supports up to 10 input images. Reve Remix/Fast Remix support up to 6 input images with XML tag references.',
        "enabled": True,
    },
    {
        "use_case_id": 'image-upscale',
        "name": 'Image Upscale',
        "description": 'Recommended models for Image Upscale',
        "models": ['creative-upscaler', 'clarity-upscaler', 'recraft-upscale'],
        "system_prompt": 'Upscale and enhance this image to higher resolution while maintaining sharpness and adding realistic detail. Preserve the original composition and style. Remove compression artifacts, enhance textures, and improve overall clarity. Suitable for print, large displays, or high-resolution viewing.',
        "prompt_tips": ['Upscale 2x-4x while maintaining quality', 'Remove compression artifacts', 'Enhance fine details and textures', 'Preserve original style and colors', 'Suitable for print or large displays'],
        "notes": '3 upscaling models. creative-upscaler adds artistic detail, clarity-upscaler enhances sharpness, recraft-upscale for maximum quality. Output size = input × scale factor.',
        "enabled": True,
    },
    {
        "use_case_id": 'instagram-post',
        "name": 'Instagram Post',
        "description": 'Recommended models for Instagram Post',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create a stunning Instagram-worthy image that stops the scroll. Vibrant colors optimized for mobile viewing, high contrast, eye-catching composition. Clean aesthetic with strong visual hierarchy. Include subtle lifestyle elements that resonate with social media audiences. Perfect for engagement and shares.',
        "sample_prompt": 'A minimalist flat lay of a morning coffee setup on a rustic wooden table, soft natural lighting, latte art, croissant on the side, cozy atmosphere, high resolution',
        "prompt_tips": ['Vibrant, scroll-stopping colors', 'High contrast for mobile screens', 'Clean, uncluttered composition', 'Lifestyle aesthetic that encourages engagement', 'Leave space for text overlays if needed'],
        "platform_sizes": {'feed_square': {'width': 1080, 'height': 1080, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Standard square post'}, 'feed_portrait': {'width': 1080, 'height': 1350, 'aspect_ratio': '4:5', 'closest_size': '768x1024', 'notes': 'Recommended - maximum visibility in feed'}, 'feed_landscape': {'width': 1080, 'height': 566, 'aspect_ratio': '1.91:1', 'closest_size': '1024x576', 'notes': 'Landscape post'}},
        "recommended_size": 'feed_portrait',
        "notes": 'Portrait 4:5 recommended for maximum feed visibility',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'instagram-story',
        "name": 'Instagram Story',
        "description": 'Recommended models for Instagram Story',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3'],
        "system_prompt": 'Create an immersive, full-screen vertical image perfect for Instagram Stories or Reels. Bold, attention-grabbing visuals that work on mobile. Dynamic composition that encourages swipe-up or engagement. Trendy aesthetic with vibrant colors. Safe zones for text overlays at top and bottom.',
        "sample_prompt": 'POV shot of someone holding a refreshing iced summer drink, beach background with palm trees, bright moody grading, vertical 9:16 format, high energy',
        "prompt_tips": ['Full-screen vertical composition (9:16)', 'Bold, attention-grabbing visuals', 'Leave safe zones for text overlays', 'Trendy, youthful aesthetic', 'High-impact first impression'],
        "platform_sizes": {'story': {'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'closest_size': '576x1024', 'notes': 'Full screen vertical story'}, 'reels': {'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'closest_size': '576x1024', 'notes': 'Instagram Reels format'}},
        "recommended_size": 'story',
        "notes": '9:16 vertical format fills entire mobile screen',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe'],
    },
    {
        "use_case_id": 'linkedin-content',
        "name": 'Linkedin Content',
        "description": 'Recommended models for Linkedin Content',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create professional, business-appropriate imagery for LinkedIn. Clean, corporate aesthetic with sophisticated look. Conveys expertise, trust, and professionalism. Suitable for thought leadership and B2B marketing. Polished, high-quality appearance.',
        "sample_prompt": 'Modern office workspace with diverse team collaborating at a glass whiteboard, bright natural light, professional attire, shallow depth of field, corporate aesthetic',
        "prompt_tips": ['Professional, corporate aesthetic', 'Clean, sophisticated composition', 'Business-appropriate imagery', 'Conveys expertise and trustworthiness', 'Suitable for B2B and thought leadership'],
        "platform_sizes": {'landscape': {'width': 1200, 'height': 627, 'aspect_ratio': '1.91:1', 'closest_size': '1024x576', 'notes': 'Standard LinkedIn post'}, 'square': {'width': 1200, 'height': 1200, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Alternative square format'}, 'portrait': {'width': 1080, 'height': 1350, 'aspect_ratio': '4:5', 'closest_size': '768x1024', 'notes': 'Mobile-optimized'}},
        "recommended_size": 'landscape',
        "notes": 'Landscape 1.91:1 is standard for LinkedIn professional content',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'logos-posters',
        "name": 'Logos Posters',
        "description": 'Recommended models for Logos Posters',
        "models": ['gemini-3-pro', 'ideogram-v3', 'flux2-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'gpt-image-1.5'],
        "system_prompt": 'Create professional logo or poster design with accurate text rendering. Clean, memorable design with perfect typography. Scalable vector-style aesthetic. Strong visual identity that works in color and monochrome. Professional quality suitable for branding and print materials.',
        "sample_prompt": "Minimalist geometric logo design for a coffee shop, vector style, black and white, clean lines, negative space, modern typography reading 'BREW'",
        "prompt_tips": ['Accurate text rendering is critical', 'Clean, memorable design', 'Works in color and monochrome', 'Scalable, vector-style look', 'Professional branding quality'],
        "platform_sizes": {'square': {'width': 1024, 'height': 1024, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Square logo/poster'}, 'portrait_poster': {'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'closest_size': '576x1024', 'notes': 'Vertical poster format'}, 'landscape_poster': {'width': 1920, 'height': 1080, 'aspect_ratio': '16:9', 'closest_size': '1024x576', 'notes': 'Horizontal poster format'}},
        "recommended_size": 'square',
        "notes": 'Nano Banana Pro excels at accurate text rendering',
        "enabled": True,
        "editing_models": ['gemini-3-pro-edit', 'flux2-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'pinterest-pins',
        "name": 'Pinterest Pins',
        "description": 'Recommended models for Pinterest Pins',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create beautiful, aspirational Pinterest-worthy imagery. Aesthetic that inspires saving and repinning. Lifestyle-focused with dreamy, curated look. Works well with text overlay for DIY, recipes, or tips. Vertical format that stands out in feed.',
        "sample_prompt": 'Cozy living room interior design, boho chic style, macrame wall hanging, indoor plants, warm beige tones, sunlight streaming through sheer curtains',
        "prompt_tips": ['Aspirational, dreamy aesthetic', 'Lifestyle-focused imagery', 'Vertical 2:3 format preferred', 'Space for text overlay if needed', 'Save-worthy and pin-worthy quality'],
        "platform_sizes": {'standard_pin': {'width': 1000, 'height': 1500, 'aspect_ratio': '2:3', 'closest_size': '768x1024', 'notes': 'Optimal Pinterest format'}, 'long_pin': {'width': 1000, 'height': 2100, 'aspect_ratio': '1:2.1', 'closest_size': '640x1536', 'notes': 'Infographic/long content'}, 'story_pin': {'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'closest_size': '576x1024', 'notes': 'Pinterest Story format'}, 'square': {'width': 1000, 'height': 1000, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Square pin option'}},
        "recommended_size": 'standard_pin',
        "notes": '2:3 aspect ratio is optimal - other ratios may get truncated',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'print-billboard',
        "name": 'Print Billboard',
        "description": 'Recommended models for Print Billboard',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create high-resolution imagery for large format print and billboard. Ultra-sharp details visible at close inspection. Bold, impactful visuals readable from distance. Clean composition with strong focal point. Premium quality suitable for outdoor advertising, posters, and signage. Consider viewing distance and environmental factors.',
        "sample_prompt": 'Gourmet burger with melting cheese and condensation on soda glass, dark moody background, food photography, macro shot, billboard quality details',
        "prompt_tips": ['Ultra-sharp, high resolution for large format', 'Bold visuals readable from distance', 'Strong focal point and clear hierarchy', 'Weather-resistant colors for outdoor use', 'Consider viewing angle and distance'],
        "platform_sizes": {'poster_a3': {'width': 1587, 'height': 2245, 'aspect_ratio': '1:1.41', 'closest_size': '768x1024', 'notes': 'A3 poster at 150 DPI'}, 'billboard_horizontal': {'width': 2400, 'height': 1200, 'aspect_ratio': '2:1', 'closest_size': '1536x640', 'notes': 'Billboard horizontal'}, 'square_print': {'width': 2000, 'height': 2000, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Square print format'}},
        "recommended_size": 'poster_a3',
        "notes": 'Generate at max resolution. Use upscaler models for 4K+ output.',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'product-listings',
        "name": 'Product Listings',
        "description": 'Recommended models for Product Listings',
        "models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
        "system_prompt": 'Enhance this product photo for e-commerce. Apply clean white or neutral background, studio-quality lighting. Make the product the hero with no distractions. Sharp focus, accurate colors, professional presentation. Suitable for Amazon, Shopify, or any e-commerce platform. Conversion-optimized, ready for listing.',
        "sample_prompt": 'High-end wireless headphones floating in mid-air, disassembled view showing components, sleek dark background, technical lighting, product visualization',
        "prompt_tips": ['Clean white/neutral background', 'Studio-quality lighting', 'Product as clear focal point', 'Sharp focus, accurate colors', 'E-commerce platform compliant'],
        "platform_sizes": {'square': {'width': 1000, 'height': 1000, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Amazon/Shopify standard'}, 'portrait': {'width': 800, 'height': 1000, 'aspect_ratio': '4:5', 'closest_size': '768x1024', 'notes': 'Vertical product shot'}},
        "recommended_size": 'square',
        "notes": '1:1 square is standard for most e-commerce platforms. Upload product photo for enhancement.',
        "enabled": True,
    },
    {
        "use_case_id": 'quick-mockups',
        "name": 'Quick Mockups',
        "description": 'Recommended models for Quick Mockups',
        "models": ['gemini-3-pro-edit', 'flux2-pro-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'reve-edit', 'reve-fast-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
        "system_prompt": 'Create a professional 3D product mockup using this image. Place the product/logo on a realistic 3D surface like a floating device, packaging box, t-shirt, mug, billboard, or business card. Add realistic shadows, reflections, and depth. Clean minimalist background with soft gradient. Professional studio lighting, photorealistic quality. Make it look like a premium product presentation or marketing asset.',
        "sample_prompt": 'Blank white t-shirt hanging on a wooden hanger against a brick wall, realistic fabric texture, soft lighting, apparel mockup',
        "prompt_tips": ['Place product on 3D surface (phone, laptop, t-shirt, mug, billboard)', 'Add realistic shadows and reflections', 'Clean minimalist or gradient background', 'Professional studio lighting', 'Floating 3D effect for modern look', 'Suitable for product presentations, marketing materials'],
        "platform_sizes": {'square': {'width': 1024, 'height': 1024, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Social media mockup'}, 'mobile': {'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'closest_size': '576x1024', 'notes': 'Mobile app mockup'}, 'desktop': {'width': 1920, 'height': 1080, 'aspect_ratio': '16:9', 'closest_size': '1024x576', 'notes': 'Desktop/website mockup'}},
        "recommended_size": 'square',
        "notes": 'Upload your product image or logo. The AI will create professional 3D mockups for marketing presentations.',
        "enabled": True,
    },
    {
        "use_case_id": 'tiktok-thumbnails',
        "name": 'Tiktok Thumbnails',
        "description": 'Recommended models for Tiktok Thumbnails',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create trendy, Gen-Z appealing content for TikTok. Bold colors, dynamic composition, youthful energy. Meme-worthy or share-worthy aesthetic. Format works in both full-screen and profile grid view. Captures attention in under 1 second.',
        "sample_prompt": 'Neon aesthetic cyberpunk street style portrait, glitch effect, vibrant pink and blue lighting, urban night scene, dynamic pose, 8k resolution',
        "prompt_tips": ['Gen-Z trendy aesthetic', 'Bold, energetic colors', 'Works in both 9:16 and 1:1 crop', 'Meme-worthy, shareable quality', 'Captures attention instantly'],
        "platform_sizes": {'vertical': {'width': 1080, 'height': 1920, 'aspect_ratio': '9:16', 'closest_size': '576x1024', 'notes': 'Full screen TikTok format'}, 'grid_preview': {'width': 1080, 'height': 1080, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'Profile grid crops to 1:1'}},
        "recommended_size": 'vertical',
        "notes": '9:16 vertical - center important elements for 1:1 grid crop',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
    {
        "use_case_id": 'vector-icons',
        "name": 'Vector Icons',
        "description": 'Recommended models for Vector Icons',
        "models": ['gemini-3-pro', 'ideogram-v3', 'flux2-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'gpt-image-1.5'],
        "system_prompt": 'Create clean, professional vector-style icon. Simple, recognizable design that works at small sizes. Consistent line weights, minimal detail. Flat design aesthetic with clear silhouette. Works on any background color. Suitable for app icons, UI elements, or infographics.',
        "sample_prompt": 'Simple flat vector icon of a rocket ship launching, blue and white color scheme, rounded corners, ui design element, isolated on white background',
        "prompt_tips": ['Simple, recognizable design', 'Works at small sizes (16px to 1024px)', 'Consistent line weights', 'Flat design, clear silhouette', 'Universal background compatibility'],
        "platform_sizes": {'icon_small': {'width': 512, 'height': 512, 'aspect_ratio': '1:1', 'closest_size': '512x512', 'notes': 'Standard icon size'}, 'icon_large': {'width': 1024, 'height': 1024, 'aspect_ratio': '1:1', 'closest_size': '1024x1024', 'notes': 'High-res icon'}},
        "recommended_size": 'icon_large',
        "notes": 'Generate large, then downscale for crisp icons',
        "enabled": True,
    },
    {
        "use_case_id": 'youtube-thumbnails',
        "name": 'Youtube Thumbnails',
        "description": 'Recommended models for Youtube Thumbnails',
        "models": ['flux2-pro', 'gemini-3-pro', 'reve', 'seedream-v4.5', 'seedream-v4', 'dreamina-v3.1', 'z-image-turbo', 'ideogram-v3', 'gpt-image-1.5'],
        "system_prompt": 'Create an extremely clickable YouTube thumbnail. Bold, contrasting colors that pop on any screen. Expressive human faces or dramatic scenes that trigger curiosity. Space for large, readable text overlay. High contrast that looks great at small sizes. Designed to maximize click-through rate and stand out in suggested videos.',
        "sample_prompt": "Shocked glowing face expression close up, red arrow pointing to mystery box, exploding background, bold yellow text 'UNBELIEVABLE', high saturation, youtube style",
        "prompt_tips": ['Bold, high-contrast colors', 'Expressive faces trigger clicks', 'Space for large text overlay', 'Works at small thumbnail sizes', 'Creates curiosity and urgency'],
        "platform_sizes": {'thumbnail_hd': {'width': 1280, 'height': 720, 'aspect_ratio': '16:9', 'closest_size': '1024x576', 'notes': 'Standard YouTube thumbnail HD'}, 'thumbnail_4k': {'width': 2560, 'height': 1440, 'aspect_ratio': '16:9', 'closest_size': '1536x640', 'notes': '4K YouTube thumbnail'}, 'landscape_16_9': {'width': 1920, 'height': 1080, 'aspect_ratio': '16:9', 'closest_size': '1024x576', 'notes': 'Full HD landscape'}},
        "recommended_size": 'thumbnail_hd',
        "notes": '16:9 landscape aspect ratio. Use editing_models when you have a base image to enhance.',
        "enabled": True,
        "editing_models": ['flux2-pro-edit', 'gemini-3-pro-edit', 'reve-edit', 'reve-fast-edit', 'seedream-v4.5-edit', 'seedream-v4-edit', 'ideogram-v3-reframe', 'gpt-image-1.5-edit'],
    },
]


def seed_models():
    # Get mongo string from env or fallback
    connection_string = os.environ.get("MONGODB_CONNECTION_STRING") or "mongodb+srv://shivraj:9nq6GM5DGHX4irNd@shivrajcluster.dv2no.mongodb.net/?retryWrites=true&w=majority"
    
    print(f"Connecting to MongoDB...")
    client = MongoClient(connection_string, tlsAllowInvalidCertificates=True)
    db = client["Grovio_Mini_Apps"]
    
    # 1. Seed Image_Models
    print("Seeding Image_Models...")
    models_collection = db["Image_Models"]
    models_collection.delete_many({})
    
    # IMAGE_MODELS should be in global scope from PRE_CONTENT
    # We write it to file, so it is global.
    if 'IMAGE_MODELS' in globals():
        models_list = globals()['IMAGE_MODELS']
        if models_list:
            models_collection.insert_many(models_list)
            print(f"Inserted {len(models_list)} models.")
    else:
        print("Warning: IMAGE_MODELS not found")

    # 2. Seed Use_Cases
    print("Seeding Use_Cases...")
    use_cases_collection = db["Use_Cases"]
    use_cases_collection.delete_many({})
    
    if USE_CASES:
        use_cases_collection.insert_many(USE_CASES)
    print(f"Inserted {len(USE_CASES)} use cases.")
    
    print("✅ Database seeded successfully!")

if __name__ == "__main__":
    seed_models()
